apiVersion: mydomain.com/v1
kind: Application
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 3
  image: nginx:latest
  port: 80
  cpu_threshold: "50%"
  memory_threshold: "128Mi"
  monitoring: true
