apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-operator
    spec:
      serviceAccountName: {{ .Release.Name }}-operator
      containers:
        - name: operator
          image: {{ .Values.image }}
          imagePullPolicy: Always
          command: ["python", "/app/deployment_operator.py"]
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "{{ .Values.kubernetesServiceHost }}"
            - name: KUBERNETES_SERVICE_PORT
              value: "{{ .Values.kubernetesServicePort }}"
